[package]
name = "miniquad"
version = "0.4.8"
authors = ["not-fl3 <not.fl3@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/not-fl3/miniquad"
repository = "https://github.com/not-fl3/miniquad"
description = """
Cross-platform window context and rendering library.
"""
readme = "README.md"
exclude = ["examples/"]
keywords = ["graphics", "3D", "opengl", "gamedev", "windowing"]
categories = ["rendering::graphics-api"]

[dependencies]
image = { version = "0.25.9", features = ["png"], default-features = false }
web-time = "1.1.0" # Okay to make it a global dep. It just falls back to std
console_error_panic_hook = "0.1.7"
tracing = "0.1.43"
anyhow = "1"
winit = { version = "0.30.12", features = ["rwh_06"] }
glow = "0.16.0"
bytemuck = "1.24.0"
tracing-subscriber = { version = "0.3.2", features = ["env-filter", "registry"] }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
glutin = "0.32.3"
glutin-winit = "0.5.0"
raw-window-handle = "0.6.2"

[target.'cfg(target_family = "wasm")'.dependencies]
web-sys = { version = "0.3.83", features = ["Response", "Location"] }
wasm-bindgen = "0.2.106"
tracing-web = "0.1.3"

[dev-dependencies]
image = { version = "0.25.9", features = ["png"], default-features = false }
glam = { version = "0.30.9", features = ["scalar-math", "bytemuck"] }
tracing = "0.1.43"
quad-rand = "0.1"