[package]
name = "mimiq"
version = "0.5.0"
authors = ["InnocentusLime <innocentuslime.help@gmail.com>", "not-fl3 <not.fl3@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/innocentuslime/miniquad"
repository = "https://github.com/innocentuslime/miniquad"
description = """
A thin OpenGL+winit wrapper for quickly making apps, inspired by miniquad
"""
readme = "README.md"
exclude = ["examples/"]
keywords = ["graphics", "3D", "opengl", "gamedev", "windowing"]
categories = ["rendering::graphics-api"]

[features]
derive = ["dep:mimiq_derive"]
serde = ["dep:serde_core", "glam-serde"]
glam-serde = ["glam/serde"]
egui = ["dep:egui", "dep:egui_glow"]

[dependencies]
image = { version = "0.25", features = ["png"], default-features = false }
web-time = "1.1" # Okay to make it a global dep. It just falls back to std
tracing = { version = "0.1", features = ["max_level_trace", "release_max_level_info"] }
glow = "0.16"
bytemuck = { version = "1.24", features = ["const_zeroed", "min_const_generics"] }
glam = { version = "0.30", features = ["scalar-math", "bytemuck"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "registry"] }
hound = "3.5"
# Opt
egui_glow = { version = "0.33", features = ["winit"], optional = true }
egui = { version = "0.33", optional = true }
serde_core = { version = "1", optional = true }
mimiq_derive = { version = "=0.5.0", path = "derive", optional = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
winit = { version = "0.30", features = ["rwh_06"] }
glutin = "0.32"
glutin-winit = "0.5"
raw-window-handle = "0.6"
cpal = "0.17.3"

[target.'cfg(target_family = "wasm")'.dependencies]
winit = "0.30" 
web-sys = { version = "0.3", features = ["Response", "Location", "ResizeObserver"] }
wasm-bindgen = "0.2.114"
tracing-web = "0.1"
console_error_panic_hook = "0.1"
cpal = { version = "0.17.3", features = ["wasm-bindgen"] }

[dev-dependencies]
quad-rand = "0.1"
serde_json = "1.0"

[profile.wasm-release]
inherits = "release"
opt-level = "z"
codegen-units = 1
lto = "thin"
strip = true
panic = "abort"

[[example]]
name = "basic_img"
path = "examples/basic_img.rs"
required-features = ["derive"]

[[example]]
name = "blobs"
path = "examples/blobs.rs"
required-features = ["derive"]

[[example]]
name = "egui"
path = "examples/egui.rs"
required-features = ["egui", "derive"]

[[example]]
name = "offscreen"
path = "examples/offscreen.rs"
required-features = ["derive"]

[[example]]
name = "post_processing"
path = "examples/post_processing.rs"
required-features = ["derive"]

[[example]]
name = "quad"
path = "examples/quad.rs"
required-features = ["derive"]

[[example]]
name = "triangle_color4b"
path = "examples/triangle_color4b.rs"
required-features = ["derive"]

[[example]]
name = "triangle_verbose"
path = "examples/triangle_verbose.rs"
required-features = ["derive"]

[[example]]
name = "triangle"
path = "examples/triangle.rs"
required-features = ["derive"]
