[package]
name = "miniquad"
version = "0.4.8"
authors = ["not-fl3 <not.fl3@gmail.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/not-fl3/miniquad"
repository = "https://github.com/not-fl3/miniquad"
description = """
Cross-platform window context and rendering library.
"""
readme = "README.md"
exclude = ["examples/"]
keywords = ["graphics", "3D", "opengl", "gamedev", "windowing"]
categories = ["rendering::graphics-api"]

[dependencies]
glutin-winit = "0.5.0"
winit = { version = "0.30.12", features = ["rwh_06"] }
glow = "0.16.0"
glutin = "0.32.3"
raw-window-handle = "0.6.2"
bytemuck = "1.24.0"

[dev-dependencies]
glam = { version = "0.30.9", features = ["scalar-math", "bytemuck"] }
quad-rand = "0.1"