on: [push, pull_request]

name: CI
jobs:
  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: '1.86.0' 
          override: true
          components: rustfmt
      - run: cargo fmt --all -- --check